---
08-00-27-0b-cf-95:
    name:  'c5.lan'
    osrel: '5.9'
    cm:    0
    lvm:   0
    patch: 1

00-1c-42-f0-6f-64:
    name:  'c64.lan'
    osrel: '6.4'
    cm:    1
    lvm:   0
    patch: 1

00-50-56-33-1a-65:
    name:  'c65.lan'
    osrel: '6.5'
    cm:    0
    lvm:   1
    patch: 0

5.9:
    server: '192.168.1.1'
    url:    'cdrom'

6.4:
    server: 'mirror.bytemark.co.uk'
    url: '/centos/6.4/os'

6.5:
  server: '192.168.1.1'
  url: 'cdrom'

